name: squawker
description: An open-source anonymous Twitter client

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 3.7.9+43

environment:
  sdk: ">=2.18.0 <3.0.0"

dependency_overrides:
  win32: ^3.0.0
  intl: ^0.17.0
  http: ^1.1.2

dependencies:
  flutter:
    sdk: flutter

  async_button_builder: ^3.0.0+1
  auto_direction: ^0.0.7
  chewie: ^1.7.5
  cryptography: ^2.7.0
  dart_twitter_api: ^0.5.8
  device_info_plus: ^9.1.1
  device_preview: ^1.1.0
  dotted_border: ^2.1.0
  extended_image: ^8.2.0
  extended_nested_scroll_view: ^6.2.1
  faker: ^2.1.0
  ffcache: ^1.1.0
  file_picker: ^5.5.0
  flex_color_scheme: ^7.3.1
  flutter_cache: ^0.1.0
  flutter_colorpicker: ^1.0.3
  flutter_file_dialog: ^3.0.2
  flutter_iconpicker_plus: ^3.2.3
  flutter_local_notifications: ^14.1.4
  flutter_localized_locales: ^2.0.5
  flutter_swipe_action_cell: ^3.1.3
  flutter_triple: ^2.2.0
  flutter_windowmanager: ^0.2.0
  hex: ^0.2.0
  html_unescape: ^2.0.0
  http: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.17.0
  logging: ^1.2.0
  logging_to_logcat: ^1.0.0
  measure_size: ^4.0.0
  media_scanner: ^2.1.0
  multi_select_flutter: ^4.1.3
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^10.4.5
  pref: ^2.7.2
  provider: ^6.1.1
  quiver: ^3.1.0
  receive_sharing_intent: ^1.4.5
  scroll_bottom_navigation_bar: ^4.0.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  socks5_proxy: ^1.0.4
  sqflite: ^2.3.2
  sqflite_common: ^2.5.3
  sqflite_migration_plan: ^1.0.0
  synchronized: ^3.1.0+1
  system_theme: ^2.3.1
  timeago: ^3.6.0
  url_launcher: ^6.2.2
  uuid: ^3.0.7
  video_player: ^2.8.3
  visibility_detector: ^0.4.0+2
  wakelock: ^0.6.2

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_oss_licenses: ^2.0.1
  intl_utils: ^2.8.7
  sqflite_common_ffi: ^2.3.2+1

flutter_MaterialSymbols:
  android: "launcher_icon"
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material MaterialSymbols font is
  # included with your application, so that you can use the MaterialSymbols in
  # the material MaterialSymbols class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/
  generate: true

flutter_intl:
  enabled: true
  class_name: L10n
